package tk.diamondbuildz.mod.character;

import com.google.common.base.Preconditions;
import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.item.ItemBlock;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.registries.IForgeRegistry;
import net.minecraftforge.registries.IForgeRegistryEntry;
import tk.diamondbuildz.mod.character.blockbases.concrete.*;
import tk.diamondbuildz.mod.character.blocks.a.glass.*;
import tk.diamondbuildz.mod.character.items.ItemBase;
import tk.diamondbuildz.mod.character.items.ItemGlassCutter;
import tk.diamondbuildz.mod.character.util.ModUtil;

import javax.annotation.Nonnull;
import java.util.Arrays;

import static tk.diamondbuildz.mod.character.init.ModBlocks.*;
import static tk.diamondbuildz.mod.character.util.Reference.MOD_ID;

/**
 * Subscribe to events that should be handled on both PHYSICAL sides in this class
 * <p>
 * Edited by Diamond; original author Cadiboo
 *
 * @author Diamond
 * @author Cadiboo -- https://github.com/Cadiboo/Example-Mod
 */
@Mod.EventBusSubscriber(modid = MOD_ID)
public final class EventSubscriber {

    // Register Blocks
    @SubscribeEvent
    public static void onRegisterBlocksEvent(@Nonnull final RegistryEvent.Register<Block> event) {
        event.getRegistry().registerAll(
                setup(new ConcreteA(), "a_concrete_black"),
                setup(new ConcreteA(), "a_concrete_blue"),
                setup(new ConcreteA(), "a_concrete_brown"),
                setup(new ConcreteA(), "a_concrete_cyan"),
                setup(new ConcreteA(), "a_concrete_gray"),
                setup(new ConcreteA(), "a_concrete_green"),
                setup(new ConcreteA(), "a_concrete_light_blue"),
                setup(new ConcreteA(), "a_concrete_lime"),
                setup(new ConcreteA(), "a_concrete_magenta"),
                setup(new ConcreteA(), "a_concrete_orange"),
                setup(new ConcreteA(), "a_concrete_pink"),
                setup(new ConcreteA(), "a_concrete_purple"),
                setup(new ConcreteA(), "a_concrete_red"),
                setup(new ConcreteA(), "a_concrete_silver"),
                setup(new ConcreteA(), "a_concrete_white"),
                setup(new ConcreteA(), "a_concrete_yellow"),

                setup(new AGlassBlack(), "a_glass_black"),
                setup(new AGlassBlue(), "a_glass_blue"),
                setup(new AGlassBrown(), "a_glass_brown"),
                setup(new AGlassClear(), "a_glass_clear"),
                setup(new AGlassCyan(), "a_glass_cyan"),
                setup(new AGlassGray(), "a_glass_gray"),
                setup(new AGlassGreen(), "a_glass_green"),
                setup(new AGlassLightBlue(), "a_glass_light_blue"),
                setup(new AGlassLime(), "a_glass_lime"),
                setup(new AGlassMagenta(), "a_glass_magenta"),
                setup(new AGlassOrange(), "a_glass_orange"),
                setup(new AGlassPink(), "a_glass_pink"),
                setup(new AGlassPurple(), "a_glass_purple"),
                setup(new AGlassRed(), "a_glass_red"),
                setup(new AGlassSilver(), "a_glass_silver"),
                setup(new AGlassWhite(), "a_glass_white"),
                setup(new AGlassYellow(), "a_glass_yellow"),

                setup(new ConcreteB(), "b_concrete_black"),
                setup(new ConcreteB(), "b_concrete_blue"),
                setup(new ConcreteB(), "b_concrete_brown"),
                setup(new ConcreteB(), "b_concrete_cyan"),
                setup(new ConcreteB(), "b_concrete_gray"),
                setup(new ConcreteB(), "b_concrete_green"),
                setup(new ConcreteB(), "b_concrete_light_blue"),
                setup(new ConcreteB(), "b_concrete_lime"),
                setup(new ConcreteB(), "b_concrete_magenta"),
                setup(new ConcreteB(), "b_concrete_orange"),
                setup(new ConcreteB(), "b_concrete_pink"),
                setup(new ConcreteB(), "b_concrete_purple"),
                setup(new ConcreteB(), "b_concrete_red"),
                setup(new ConcreteB(), "b_concrete_silver"),
                setup(new ConcreteB(), "b_concrete_white"),
                setup(new ConcreteB(), "b_concrete_yellow"),

                setup(new ConcreteC(), "c_concrete_black"),
                setup(new ConcreteC(), "c_concrete_blue"),
                setup(new ConcreteC(), "c_concrete_brown"),
                setup(new ConcreteC(), "c_concrete_cyan"),
                setup(new ConcreteC(), "c_concrete_gray"),
                setup(new ConcreteC(), "c_concrete_green"),
                setup(new ConcreteC(), "c_concrete_light_blue"),
                setup(new ConcreteC(), "c_concrete_lime"),
                setup(new ConcreteC(), "c_concrete_magenta"),
                setup(new ConcreteC(), "c_concrete_orange"),
                setup(new ConcreteC(), "c_concrete_pink"),
                setup(new ConcreteC(), "c_concrete_purple"),
                setup(new ConcreteC(), "c_concrete_red"),
                setup(new ConcreteC(), "c_concrete_silver"),
                setup(new ConcreteC(), "c_concrete_white"),
                setup(new ConcreteC(), "c_concrete_yellow"),

                setup(new ConcreteD(), "d_concrete_black"),
                setup(new ConcreteD(), "d_concrete_blue"),
                setup(new ConcreteD(), "d_concrete_brown"),
                setup(new ConcreteD(), "d_concrete_cyan"),
                setup(new ConcreteD(), "d_concrete_gray"),
                setup(new ConcreteD(), "d_concrete_green"),
                setup(new ConcreteD(), "d_concrete_light_blue"),
                setup(new ConcreteD(), "d_concrete_lime"),
                setup(new ConcreteD(), "d_concrete_magenta"),
                setup(new ConcreteD(), "d_concrete_orange"),
                setup(new ConcreteD(), "d_concrete_pink"),
                setup(new ConcreteD(), "d_concrete_purple"),
                setup(new ConcreteD(), "d_concrete_red"),
                setup(new ConcreteD(), "d_concrete_silver"),
                setup(new ConcreteD(), "d_concrete_white"),
                setup(new ConcreteD(), "d_concrete_yellow"),

                setup(new ConcreteE(), "e_concrete_black"),
                setup(new ConcreteE(), "e_concrete_blue"),
                setup(new ConcreteE(), "e_concrete_brown"),
                setup(new ConcreteE(), "e_concrete_cyan"),
                setup(new ConcreteE(), "e_concrete_gray"),
                setup(new ConcreteE(), "e_concrete_green"),
                setup(new ConcreteE(), "e_concrete_light_blue"),
                setup(new ConcreteE(), "e_concrete_lime"),
                setup(new ConcreteE(), "e_concrete_magenta"),
                setup(new ConcreteE(), "e_concrete_orange"),
                setup(new ConcreteE(), "e_concrete_pink"),
                setup(new ConcreteE(), "e_concrete_purple"),
                setup(new ConcreteE(), "e_concrete_red"),
                setup(new ConcreteE(), "e_concrete_silver"),
                setup(new ConcreteE(), "e_concrete_white"),
                setup(new ConcreteE(), "e_concrete_yellow"),

                setup(new ConcreteF(), "f_concrete_black"),
                setup(new ConcreteF(), "f_concrete_blue"),
                setup(new ConcreteF(), "f_concrete_brown"),
                setup(new ConcreteF(), "f_concrete_cyan"),
                setup(new ConcreteF(), "f_concrete_gray"),
                setup(new ConcreteF(), "f_concrete_green"),
                setup(new ConcreteF(), "f_concrete_light_blue"),
                setup(new ConcreteF(), "f_concrete_lime"),
                setup(new ConcreteF(), "f_concrete_magenta"),
                setup(new ConcreteF(), "f_concrete_orange"),
                setup(new ConcreteF(), "f_concrete_pink"),
                setup(new ConcreteF(), "f_concrete_purple"),
                setup(new ConcreteF(), "f_concrete_red"),
                setup(new ConcreteF(), "f_concrete_silver"),
                setup(new ConcreteF(), "f_concrete_white"),
                setup(new ConcreteF(), "f_concrete_yellow"),

                setup(new ConcreteG(), "g_concrete_black"),
                setup(new ConcreteG(), "g_concrete_blue"),
                setup(new ConcreteG(), "g_concrete_brown"),
                setup(new ConcreteG(), "g_concrete_cyan"),
                setup(new ConcreteG(), "g_concrete_gray"),
                setup(new ConcreteG(), "g_concrete_green"),
                setup(new ConcreteG(), "g_concrete_light_blue"),
                setup(new ConcreteG(), "g_concrete_lime"),
                setup(new ConcreteG(), "g_concrete_magenta"),
                setup(new ConcreteG(), "g_concrete_orange"),
                setup(new ConcreteG(), "g_concrete_pink"),
                setup(new ConcreteG(), "g_concrete_purple"),
                setup(new ConcreteG(), "g_concrete_red"),
                setup(new ConcreteG(), "g_concrete_silver"),
                setup(new ConcreteG(), "g_concrete_white"),
                setup(new ConcreteG(), "g_concrete_yellow"),

                setup(new ConcreteH(), "h_concrete_black"),
                setup(new ConcreteH(), "h_concrete_blue"),
                setup(new ConcreteH(), "h_concrete_brown"),
                setup(new ConcreteH(), "h_concrete_cyan"),
                setup(new ConcreteH(), "h_concrete_gray"),
                setup(new ConcreteH(), "h_concrete_green"),
                setup(new ConcreteH(), "h_concrete_light_blue"),
                setup(new ConcreteH(), "h_concrete_lime"),
                setup(new ConcreteH(), "h_concrete_magenta"),
                setup(new ConcreteH(), "h_concrete_orange"),
                setup(new ConcreteH(), "h_concrete_pink"),
                setup(new ConcreteH(), "h_concrete_purple"),
                setup(new ConcreteH(), "h_concrete_red"),
                setup(new ConcreteH(), "h_concrete_silver"),
                setup(new ConcreteH(), "h_concrete_white"),
                setup(new ConcreteH(), "h_concrete_yellow"),

                setup(new ConcreteI(), "i_concrete_black"),
                setup(new ConcreteI(), "i_concrete_blue"),
                setup(new ConcreteI(), "i_concrete_brown"),
                setup(new ConcreteI(), "i_concrete_cyan"),
                setup(new ConcreteI(), "i_concrete_gray"),
                setup(new ConcreteI(), "i_concrete_green"),
                setup(new ConcreteI(), "i_concrete_light_blue"),
                setup(new ConcreteI(), "i_concrete_lime"),
                setup(new ConcreteI(), "i_concrete_magenta"),
                setup(new ConcreteI(), "i_concrete_orange"),
                setup(new ConcreteI(), "i_concrete_pink"),
                setup(new ConcreteI(), "i_concrete_purple"),
                setup(new ConcreteI(), "i_concrete_red"),
                setup(new ConcreteI(), "i_concrete_silver"),
                setup(new ConcreteI(), "i_concrete_white"),
                setup(new ConcreteI(), "i_concrete_yellow"),

                setup(new ConcreteJ(), "j_concrete_black"),
                setup(new ConcreteJ(), "j_concrete_blue"),
                setup(new ConcreteJ(), "j_concrete_brown"),
                setup(new ConcreteJ(), "j_concrete_cyan"),
                setup(new ConcreteJ(), "j_concrete_gray"),
                setup(new ConcreteJ(), "j_concrete_green"),
                setup(new ConcreteJ(), "j_concrete_light_blue"),
                setup(new ConcreteJ(), "j_concrete_lime"),
                setup(new ConcreteJ(), "j_concrete_magenta"),
                setup(new ConcreteJ(), "j_concrete_orange"),
                setup(new ConcreteJ(), "j_concrete_pink"),
                setup(new ConcreteJ(), "j_concrete_purple"),
                setup(new ConcreteJ(), "j_concrete_red"),
                setup(new ConcreteJ(), "j_concrete_silver"),
                setup(new ConcreteJ(), "j_concrete_white"),
                setup(new ConcreteJ(), "j_concrete_yellow"),

                setup(new ConcreteK(), "k_concrete_black"),
                setup(new ConcreteK(), "k_concrete_blue"),
                setup(new ConcreteK(), "k_concrete_brown"),
                setup(new ConcreteK(), "k_concrete_cyan"),
                setup(new ConcreteK(), "k_concrete_gray"),
                setup(new ConcreteK(), "k_concrete_green"),
                setup(new ConcreteK(), "k_concrete_light_blue"),
                setup(new ConcreteK(), "k_concrete_lime"),
                setup(new ConcreteK(), "k_concrete_magenta"),
                setup(new ConcreteK(), "k_concrete_orange"),
                setup(new ConcreteK(), "k_concrete_pink"),
                setup(new ConcreteK(), "k_concrete_purple"),
                setup(new ConcreteK(), "k_concrete_red"),
                setup(new ConcreteK(), "k_concrete_silver"),
                setup(new ConcreteK(), "k_concrete_white"),
                setup(new ConcreteK(), "k_concrete_yellow"),

                setup(new ConcreteL(), "l_concrete_black"),
                setup(new ConcreteL(), "l_concrete_blue"),
                setup(new ConcreteL(), "l_concrete_brown"),
                setup(new ConcreteL(), "l_concrete_cyan"),
                setup(new ConcreteL(), "l_concrete_gray"),
                setup(new ConcreteL(), "l_concrete_green"),
                setup(new ConcreteL(), "l_concrete_light_blue"),
                setup(new ConcreteL(), "l_concrete_lime"),
                setup(new ConcreteL(), "l_concrete_magenta"),
                setup(new ConcreteL(), "l_concrete_orange"),
                setup(new ConcreteL(), "l_concrete_pink"),
                setup(new ConcreteL(), "l_concrete_purple"),
                setup(new ConcreteL(), "l_concrete_red"),
                setup(new ConcreteL(), "l_concrete_silver"),
                setup(new ConcreteL(), "l_concrete_white"),
                setup(new ConcreteL(), "l_concrete_yellow"),

                setup(new ConcreteM(), "m_concrete_black"),
                setup(new ConcreteM(), "m_concrete_blue"),
                setup(new ConcreteM(), "m_concrete_brown"),
                setup(new ConcreteM(), "m_concrete_cyan"),
                setup(new ConcreteM(), "m_concrete_gray"),
                setup(new ConcreteM(), "m_concrete_green"),
                setup(new ConcreteM(), "m_concrete_light_blue"),
                setup(new ConcreteM(), "m_concrete_lime"),
                setup(new ConcreteM(), "m_concrete_magenta"),
                setup(new ConcreteM(), "m_concrete_orange"),
                setup(new ConcreteM(), "m_concrete_pink"),
                setup(new ConcreteM(), "m_concrete_purple"),
                setup(new ConcreteM(), "m_concrete_red"),
                setup(new ConcreteM(), "m_concrete_silver"),
                setup(new ConcreteM(), "m_concrete_white"),
                setup(new ConcreteM(), "m_concrete_yellow"),

                setup(new ConcreteN(), "n_concrete_black"),
                setup(new ConcreteN(), "n_concrete_blue"),
                setup(new ConcreteN(), "n_concrete_brown"),
                setup(new ConcreteN(), "n_concrete_cyan"),
                setup(new ConcreteN(), "n_concrete_gray"),
                setup(new ConcreteN(), "n_concrete_green"),
                setup(new ConcreteN(), "n_concrete_light_blue"),
                setup(new ConcreteN(), "n_concrete_lime"),
                setup(new ConcreteN(), "n_concrete_magenta"),
                setup(new ConcreteN(), "n_concrete_orange"),
                setup(new ConcreteN(), "n_concrete_pink"),
                setup(new ConcreteN(), "n_concrete_purple"),
                setup(new ConcreteN(), "n_concrete_red"),
                setup(new ConcreteN(), "n_concrete_silver"),
                setup(new ConcreteN(), "n_concrete_white"),
                setup(new ConcreteN(), "n_concrete_yellow"),

                setup(new ConcreteO(), "o_concrete_black"),
                setup(new ConcreteO(), "o_concrete_blue"),
                setup(new ConcreteO(), "o_concrete_brown"),
                setup(new ConcreteO(), "o_concrete_cyan"),
                setup(new ConcreteO(), "o_concrete_gray"),
                setup(new ConcreteO(), "o_concrete_green"),
                setup(new ConcreteO(), "o_concrete_light_blue"),
                setup(new ConcreteO(), "o_concrete_lime"),
                setup(new ConcreteO(), "o_concrete_magenta"),
                setup(new ConcreteO(), "o_concrete_orange"),
                setup(new ConcreteO(), "o_concrete_pink"),
                setup(new ConcreteO(), "o_concrete_purple"),
                setup(new ConcreteO(), "o_concrete_red"),
                setup(new ConcreteO(), "o_concrete_silver"),
                setup(new ConcreteO(), "o_concrete_white"),
                setup(new ConcreteO(), "o_concrete_yellow"),

                setup(new ConcreteP(), "p_concrete_black"),
                setup(new ConcreteP(), "p_concrete_blue"),
                setup(new ConcreteP(), "p_concrete_brown"),
                setup(new ConcreteP(), "p_concrete_cyan"),
                setup(new ConcreteP(), "p_concrete_gray"),
                setup(new ConcreteP(), "p_concrete_green"),
                setup(new ConcreteP(), "p_concrete_light_blue"),
                setup(new ConcreteP(), "p_concrete_lime"),
                setup(new ConcreteP(), "p_concrete_magenta"),
                setup(new ConcreteP(), "p_concrete_orange"),
                setup(new ConcreteP(), "p_concrete_pink"),
                setup(new ConcreteP(), "p_concrete_purple"),
                setup(new ConcreteP(), "p_concrete_red"),
                setup(new ConcreteP(), "p_concrete_silver"),
                setup(new ConcreteP(), "p_concrete_white"),
                setup(new ConcreteP(), "p_concrete_yellow"),

                setup(new ConcreteQ(), "q_concrete_black"),
                setup(new ConcreteQ(), "q_concrete_blue"),
                setup(new ConcreteQ(), "q_concrete_brown"),
                setup(new ConcreteQ(), "q_concrete_cyan"),
                setup(new ConcreteQ(), "q_concrete_gray"),
                setup(new ConcreteQ(), "q_concrete_green"),
                setup(new ConcreteQ(), "q_concrete_light_blue"),
                setup(new ConcreteQ(), "q_concrete_lime"),
                setup(new ConcreteQ(), "q_concrete_magenta"),
                setup(new ConcreteQ(), "q_concrete_orange"),
                setup(new ConcreteQ(), "q_concrete_pink"),
                setup(new ConcreteQ(), "q_concrete_purple"),
                setup(new ConcreteQ(), "q_concrete_red"),
                setup(new ConcreteQ(), "q_concrete_silver"),
                setup(new ConcreteQ(), "q_concrete_white"),
                setup(new ConcreteQ(), "q_concrete_yellow"),

                setup(new ConcreteR(), "r_concrete_black"),
                setup(new ConcreteR(), "r_concrete_blue"),
                setup(new ConcreteR(), "r_concrete_brown"),
                setup(new ConcreteR(), "r_concrete_cyan"),
                setup(new ConcreteR(), "r_concrete_gray"),
                setup(new ConcreteR(), "r_concrete_green"),
                setup(new ConcreteR(), "r_concrete_light_blue"),
                setup(new ConcreteR(), "r_concrete_lime"),
                setup(new ConcreteR(), "r_concrete_magenta"),
                setup(new ConcreteR(), "r_concrete_orange"),
                setup(new ConcreteR(), "r_concrete_pink"),
                setup(new ConcreteR(), "r_concrete_purple"),
                setup(new ConcreteR(), "r_concrete_red"),
                setup(new ConcreteR(), "r_concrete_silver"),
                setup(new ConcreteR(), "r_concrete_white"),
                setup(new ConcreteR(), "r_concrete_yellow"),

                setup(new ConcreteS(), "s_concrete_black"),
                setup(new ConcreteS(), "s_concrete_blue"),
                setup(new ConcreteS(), "s_concrete_brown"),
                setup(new ConcreteS(), "s_concrete_cyan"),
                setup(new ConcreteS(), "s_concrete_gray"),
                setup(new ConcreteS(), "s_concrete_green"),
                setup(new ConcreteS(), "s_concrete_light_blue"),
                setup(new ConcreteS(), "s_concrete_lime"),
                setup(new ConcreteS(), "s_concrete_magenta"),
                setup(new ConcreteS(), "s_concrete_orange"),
                setup(new ConcreteS(), "s_concrete_pink"),
                setup(new ConcreteS(), "s_concrete_purple"),
                setup(new ConcreteS(), "s_concrete_red"),
                setup(new ConcreteS(), "s_concrete_silver"),
                setup(new ConcreteS(), "s_concrete_white"),
                setup(new ConcreteS(), "s_concrete_yellow"),

                setup(new ConcreteT(), "t_concrete_black"),
                setup(new ConcreteT(), "t_concrete_blue"),
                setup(new ConcreteT(), "t_concrete_brown"),
                setup(new ConcreteT(), "t_concrete_cyan"),
                setup(new ConcreteT(), "t_concrete_gray"),
                setup(new ConcreteT(), "t_concrete_green"),
                setup(new ConcreteT(), "t_concrete_light_blue"),
                setup(new ConcreteT(), "t_concrete_lime"),
                setup(new ConcreteT(), "t_concrete_magenta"),
                setup(new ConcreteT(), "t_concrete_orange"),
                setup(new ConcreteT(), "t_concrete_pink"),
                setup(new ConcreteT(), "t_concrete_purple"),
                setup(new ConcreteT(), "t_concrete_red"),
                setup(new ConcreteT(), "t_concrete_silver"),
                setup(new ConcreteT(), "t_concrete_white"),
                setup(new ConcreteT(), "t_concrete_yellow"),

                setup(new ConcreteU(), "u_concrete_black"),
                setup(new ConcreteU(), "u_concrete_blue"),
                setup(new ConcreteU(), "u_concrete_brown"),
                setup(new ConcreteU(), "u_concrete_cyan"),
                setup(new ConcreteU(), "u_concrete_gray"),
                setup(new ConcreteU(), "u_concrete_green"),
                setup(new ConcreteU(), "u_concrete_light_blue"),
                setup(new ConcreteU(), "u_concrete_lime"),
                setup(new ConcreteU(), "u_concrete_magenta"),
                setup(new ConcreteU(), "u_concrete_orange"),
                setup(new ConcreteU(), "u_concrete_pink"),
                setup(new ConcreteU(), "u_concrete_purple"),
                setup(new ConcreteU(), "u_concrete_red"),
                setup(new ConcreteU(), "u_concrete_silver"),
                setup(new ConcreteU(), "u_concrete_white"),
                setup(new ConcreteU(), "u_concrete_yellow"),

                setup(new ConcreteV(), "v_concrete_black"),
                setup(new ConcreteV(), "v_concrete_blue"),
                setup(new ConcreteV(), "v_concrete_brown"),
                setup(new ConcreteV(), "v_concrete_cyan"),
                setup(new ConcreteV(), "v_concrete_gray"),
                setup(new ConcreteV(), "v_concrete_green"),
                setup(new ConcreteV(), "v_concrete_light_blue"),
                setup(new ConcreteV(), "v_concrete_lime"),
                setup(new ConcreteV(), "v_concrete_magenta"),
                setup(new ConcreteV(), "v_concrete_orange"),
                setup(new ConcreteV(), "v_concrete_pink"),
                setup(new ConcreteV(), "v_concrete_purple"),
                setup(new ConcreteV(), "v_concrete_red"),
                setup(new ConcreteV(), "v_concrete_silver"),
                setup(new ConcreteV(), "v_concrete_white"),
                setup(new ConcreteV(), "v_concrete_yellow"),

                setup(new ConcreteW(), "w_concrete_black"),
                setup(new ConcreteW(), "w_concrete_blue"),
                setup(new ConcreteW(), "w_concrete_brown"),
                setup(new ConcreteW(), "w_concrete_cyan"),
                setup(new ConcreteW(), "w_concrete_gray"),
                setup(new ConcreteW(), "w_concrete_green"),
                setup(new ConcreteW(), "w_concrete_light_blue"),
                setup(new ConcreteW(), "w_concrete_lime"),
                setup(new ConcreteW(), "w_concrete_magenta"),
                setup(new ConcreteW(), "w_concrete_orange"),
                setup(new ConcreteW(), "w_concrete_pink"),
                setup(new ConcreteW(), "w_concrete_purple"),
                setup(new ConcreteW(), "w_concrete_red"),
                setup(new ConcreteW(), "w_concrete_silver"),
                setup(new ConcreteW(), "w_concrete_white"),
                setup(new ConcreteW(), "w_concrete_yellow"),

                setup(new ConcreteX(), "x_concrete_black"),
                setup(new ConcreteX(), "x_concrete_blue"),
                setup(new ConcreteX(), "x_concrete_brown"),
                setup(new ConcreteX(), "x_concrete_cyan"),
                setup(new ConcreteX(), "x_concrete_gray"),
                setup(new ConcreteX(), "x_concrete_green"),
                setup(new ConcreteX(), "x_concrete_light_blue"),
                setup(new ConcreteX(), "x_concrete_lime"),
                setup(new ConcreteX(), "x_concrete_magenta"),
                setup(new ConcreteX(), "x_concrete_orange"),
                setup(new ConcreteX(), "x_concrete_pink"),
                setup(new ConcreteX(), "x_concrete_purple"),
                setup(new ConcreteX(), "x_concrete_red"),
                setup(new ConcreteX(), "x_concrete_silver"),
                setup(new ConcreteX(), "x_concrete_white"),
                setup(new ConcreteX(), "x_concrete_yellow"),

                setup(new ConcreteY(), "y_concrete_black"),
                setup(new ConcreteY(), "y_concrete_blue"),
                setup(new ConcreteY(), "y_concrete_brown"),
                setup(new ConcreteY(), "y_concrete_cyan"),
                setup(new ConcreteY(), "y_concrete_gray"),
                setup(new ConcreteY(), "y_concrete_green"),
                setup(new ConcreteY(), "y_concrete_light_blue"),
                setup(new ConcreteY(), "y_concrete_lime"),
                setup(new ConcreteY(), "y_concrete_magenta"),
                setup(new ConcreteY(), "y_concrete_orange"),
                setup(new ConcreteY(), "y_concrete_pink"),
                setup(new ConcreteY(), "y_concrete_purple"),
                setup(new ConcreteY(), "y_concrete_red"),
                setup(new ConcreteY(), "y_concrete_silver"),
                setup(new ConcreteY(), "y_concrete_white"),
                setup(new ConcreteY(), "y_concrete_yellow"),

                setup(new ConcreteZ(), "z_concrete_black"),
                setup(new ConcreteZ(), "z_concrete_blue"),
                setup(new ConcreteZ(), "z_concrete_brown"),
                setup(new ConcreteZ(), "z_concrete_cyan"),
                setup(new ConcreteZ(), "z_concrete_gray"),
                setup(new ConcreteZ(), "z_concrete_green"),
                setup(new ConcreteZ(), "z_concrete_light_blue"),
                setup(new ConcreteZ(), "z_concrete_lime"),
                setup(new ConcreteZ(), "z_concrete_magenta"),
                setup(new ConcreteZ(), "z_concrete_orange"),
                setup(new ConcreteZ(), "z_concrete_pink"),
                setup(new ConcreteZ(), "z_concrete_purple"),
                setup(new ConcreteZ(), "z_concrete_red"),
                setup(new ConcreteZ(), "z_concrete_silver"),
                setup(new ConcreteZ(), "z_concrete_white"),
                setup(new ConcreteZ(), "z_concrete_yellow")
                
        );
        Main.CHARACTER_MOD_LOG.debug("Registered blocks");
    }

    // Register Item Blocks/Items
    @SubscribeEvent
    public static void onRegisterItemsEvent(@Nonnull final RegistryEvent.Register<Item> event) {
        final IForgeRegistry<Item> registry = event.getRegistry();

        // Item Blocks
        Arrays.stream(new Block[]{

                A_CONCRETE_BLACK,
                A_CONCRETE_BLUE,
                A_CONCRETE_BROWN,
                A_CONCRETE_CYAN,
                A_CONCRETE_GRAY,
                A_CONCRETE_GREEN,
                A_CONCRETE_LIGHT_BLUE,
                A_CONCRETE_LIME,
                A_CONCRETE_MAGENTA,
                A_CONCRETE_ORANGE,
                A_CONCRETE_PINK,
                A_CONCRETE_PURPLE,
                A_CONCRETE_RED,
                A_CONCRETE_SILVER,
                A_CONCRETE_WHITE,
                A_CONCRETE_YELLOW,

                A_GLASS_BLACK,
                A_GLASS_BLUE,
                A_GLASS_BROWN,
                A_GLASS_CLEAR,
                A_GLASS_CYAN,
                A_GLASS_GRAY,
                A_GLASS_GREEN,
                A_GLASS_LIGHT_BLUE,
                A_GLASS_LIME,
                A_GLASS_MAGENTA,
                A_GLASS_ORANGE,
                A_GLASS_PINK,
                A_GLASS_PURPLE,
                A_GLASS_RED,
                A_GLASS_SILVER,
                A_GLASS_WHITE,
                A_GLASS_YELLOW,

                B_CONCRETE_BLACK,
                B_CONCRETE_BLUE,
                B_CONCRETE_BROWN,
                B_CONCRETE_CYAN,
                B_CONCRETE_GRAY,
                B_CONCRETE_GREEN,
                B_CONCRETE_LIGHT_BLUE,
                B_CONCRETE_LIME,
                B_CONCRETE_MAGENTA,
                B_CONCRETE_ORANGE,
                B_CONCRETE_PINK,
                B_CONCRETE_PURPLE,
                B_CONCRETE_RED,
                B_CONCRETE_SILVER,
                B_CONCRETE_WHITE,
                B_CONCRETE_YELLOW,

                C_CONCRETE_BLACK,
                C_CONCRETE_BLUE,
                C_CONCRETE_BROWN,
                C_CONCRETE_CYAN,
                C_CONCRETE_GRAY,
                C_CONCRETE_GREEN,
                C_CONCRETE_LIGHT_BLUE,
                C_CONCRETE_LIME,
                C_CONCRETE_MAGENTA,
                C_CONCRETE_ORANGE,
                C_CONCRETE_PINK,
                C_CONCRETE_PURPLE,
                C_CONCRETE_RED,
                C_CONCRETE_SILVER,
                C_CONCRETE_WHITE,
                C_CONCRETE_YELLOW,

                D_CONCRETE_BLACK,
                D_CONCRETE_BLUE,
                D_CONCRETE_BROWN,
                D_CONCRETE_CYAN,
                D_CONCRETE_GRAY,
                D_CONCRETE_GREEN,
                D_CONCRETE_LIGHT_BLUE,
                D_CONCRETE_LIME,
                D_CONCRETE_MAGENTA,
                D_CONCRETE_ORANGE,
                D_CONCRETE_PINK,
                D_CONCRETE_PURPLE,
                D_CONCRETE_RED,
                D_CONCRETE_SILVER,
                D_CONCRETE_WHITE,
                D_CONCRETE_YELLOW,

                E_CONCRETE_BLACK,
                E_CONCRETE_BLUE,
                E_CONCRETE_BROWN,
                E_CONCRETE_CYAN,
                E_CONCRETE_GRAY,
                E_CONCRETE_GREEN,
                E_CONCRETE_LIGHT_BLUE,
                E_CONCRETE_LIME,
                E_CONCRETE_MAGENTA,
                E_CONCRETE_ORANGE,
                E_CONCRETE_PINK,
                E_CONCRETE_PURPLE,
                E_CONCRETE_RED,
                E_CONCRETE_SILVER,
                E_CONCRETE_WHITE,
                E_CONCRETE_YELLOW,

                F_CONCRETE_BLACK,
                F_CONCRETE_BLUE,
                F_CONCRETE_BROWN,
                F_CONCRETE_CYAN,
                F_CONCRETE_GRAY,
                F_CONCRETE_GREEN,
                F_CONCRETE_LIGHT_BLUE,
                F_CONCRETE_LIME,
                F_CONCRETE_MAGENTA,
                F_CONCRETE_ORANGE,
                F_CONCRETE_PINK,
                F_CONCRETE_PURPLE,
                F_CONCRETE_RED,
                F_CONCRETE_SILVER,
                F_CONCRETE_WHITE,
                F_CONCRETE_YELLOW,

                G_CONCRETE_BLACK,
                G_CONCRETE_BLUE,
                G_CONCRETE_BROWN,
                G_CONCRETE_CYAN,
                G_CONCRETE_GRAY,
                G_CONCRETE_GREEN,
                G_CONCRETE_LIGHT_BLUE,
                G_CONCRETE_LIME,
                G_CONCRETE_MAGENTA,
                G_CONCRETE_ORANGE,
                G_CONCRETE_PINK,
                G_CONCRETE_PURPLE,
                G_CONCRETE_RED,
                G_CONCRETE_SILVER,
                G_CONCRETE_WHITE,
                G_CONCRETE_YELLOW,

                H_CONCRETE_BLACK,
                H_CONCRETE_BLUE,
                H_CONCRETE_BROWN,
                H_CONCRETE_CYAN,
                H_CONCRETE_GRAY,
                H_CONCRETE_GREEN,
                H_CONCRETE_LIGHT_BLUE,
                H_CONCRETE_LIME,
                H_CONCRETE_MAGENTA,
                H_CONCRETE_ORANGE,
                H_CONCRETE_PINK,
                H_CONCRETE_PURPLE,
                H_CONCRETE_RED,
                H_CONCRETE_SILVER,
                H_CONCRETE_WHITE,
                H_CONCRETE_YELLOW,

                I_CONCRETE_BLACK,
                I_CONCRETE_BLUE,
                I_CONCRETE_BROWN,
                I_CONCRETE_CYAN,
                I_CONCRETE_GRAY,
                I_CONCRETE_GREEN,
                I_CONCRETE_LIGHT_BLUE,
                I_CONCRETE_LIME,
                I_CONCRETE_MAGENTA,
                I_CONCRETE_ORANGE,
                I_CONCRETE_PINK,
                I_CONCRETE_PURPLE,
                I_CONCRETE_RED,
                I_CONCRETE_SILVER,
                I_CONCRETE_WHITE,
                I_CONCRETE_YELLOW,

                J_CONCRETE_BLACK,
                J_CONCRETE_BLUE,
                J_CONCRETE_BROWN,
                J_CONCRETE_CYAN,
                J_CONCRETE_GRAY,
                J_CONCRETE_GREEN,
                J_CONCRETE_LIGHT_BLUE,
                J_CONCRETE_LIME,
                J_CONCRETE_MAGENTA,
                J_CONCRETE_ORANGE,
                J_CONCRETE_PINK,
                J_CONCRETE_PURPLE,
                J_CONCRETE_RED,
                J_CONCRETE_SILVER,
                J_CONCRETE_WHITE,
                J_CONCRETE_YELLOW,

                K_CONCRETE_BLACK,
                K_CONCRETE_BLUE,
                K_CONCRETE_BROWN,
                K_CONCRETE_CYAN,
                K_CONCRETE_GRAY,
                K_CONCRETE_GREEN,
                K_CONCRETE_LIGHT_BLUE,
                K_CONCRETE_LIME,
                K_CONCRETE_MAGENTA,
                K_CONCRETE_ORANGE,
                K_CONCRETE_PINK,
                K_CONCRETE_PURPLE,
                K_CONCRETE_RED,
                K_CONCRETE_SILVER,
                K_CONCRETE_WHITE,
                K_CONCRETE_YELLOW,

                L_CONCRETE_BLACK,
                L_CONCRETE_BLUE,
                L_CONCRETE_BROWN,
                L_CONCRETE_CYAN,
                L_CONCRETE_GRAY,
                L_CONCRETE_GREEN,
                L_CONCRETE_LIGHT_BLUE,
                L_CONCRETE_LIME,
                L_CONCRETE_MAGENTA,
                L_CONCRETE_ORANGE,
                L_CONCRETE_PINK,
                L_CONCRETE_PURPLE,
                L_CONCRETE_RED,
                L_CONCRETE_SILVER,
                L_CONCRETE_WHITE,
                L_CONCRETE_YELLOW,

                M_CONCRETE_BLACK,
                M_CONCRETE_BLUE,
                M_CONCRETE_BROWN,
                M_CONCRETE_CYAN,
                M_CONCRETE_GRAY,
                M_CONCRETE_GREEN,
                M_CONCRETE_LIGHT_BLUE,
                M_CONCRETE_LIME,
                M_CONCRETE_MAGENTA,
                M_CONCRETE_ORANGE,
                M_CONCRETE_PINK,
                M_CONCRETE_PURPLE,
                M_CONCRETE_RED,
                M_CONCRETE_SILVER,
                M_CONCRETE_WHITE,
                M_CONCRETE_YELLOW,

                N_CONCRETE_BLACK,
                N_CONCRETE_BLUE,
                N_CONCRETE_BROWN,
                N_CONCRETE_CYAN,
                N_CONCRETE_GRAY,
                N_CONCRETE_GREEN,
                N_CONCRETE_LIGHT_BLUE,
                N_CONCRETE_LIME,
                N_CONCRETE_MAGENTA,
                N_CONCRETE_ORANGE,
                N_CONCRETE_PINK,
                N_CONCRETE_PURPLE,
                N_CONCRETE_RED,
                N_CONCRETE_SILVER,
                N_CONCRETE_WHITE,
                N_CONCRETE_YELLOW,

                O_CONCRETE_BLACK,
                O_CONCRETE_BLUE,
                O_CONCRETE_BROWN,
                O_CONCRETE_CYAN,
                O_CONCRETE_GRAY,
                O_CONCRETE_GREEN,
                O_CONCRETE_LIGHT_BLUE,
                O_CONCRETE_LIME,
                O_CONCRETE_MAGENTA,
                O_CONCRETE_ORANGE,
                O_CONCRETE_PINK,
                O_CONCRETE_PURPLE,
                O_CONCRETE_RED,
                O_CONCRETE_SILVER,
                O_CONCRETE_WHITE,
                O_CONCRETE_YELLOW,

                P_CONCRETE_BLACK,
                P_CONCRETE_BLUE,
                P_CONCRETE_BROWN,
                P_CONCRETE_CYAN,
                P_CONCRETE_GRAY,
                P_CONCRETE_GREEN,
                P_CONCRETE_LIGHT_BLUE,
                P_CONCRETE_LIME,
                P_CONCRETE_MAGENTA,
                P_CONCRETE_ORANGE,
                P_CONCRETE_PINK,
                P_CONCRETE_PURPLE,
                P_CONCRETE_RED,
                P_CONCRETE_SILVER,
                P_CONCRETE_WHITE,
                P_CONCRETE_YELLOW,

                Q_CONCRETE_BLACK,
                Q_CONCRETE_BLUE,
                Q_CONCRETE_BROWN,
                Q_CONCRETE_CYAN,
                Q_CONCRETE_GRAY,
                Q_CONCRETE_GREEN,
                Q_CONCRETE_LIGHT_BLUE,
                Q_CONCRETE_LIME,
                Q_CONCRETE_MAGENTA,
                Q_CONCRETE_ORANGE,
                Q_CONCRETE_PINK,
                Q_CONCRETE_PURPLE,
                Q_CONCRETE_RED,
                Q_CONCRETE_SILVER,
                Q_CONCRETE_WHITE,
                Q_CONCRETE_YELLOW,

                R_CONCRETE_BLACK,
                R_CONCRETE_BLUE,
                R_CONCRETE_BROWN,
                R_CONCRETE_CYAN,
                R_CONCRETE_GRAY,
                R_CONCRETE_GREEN,
                R_CONCRETE_LIGHT_BLUE,
                R_CONCRETE_LIME,
                R_CONCRETE_MAGENTA,
                R_CONCRETE_ORANGE,
                R_CONCRETE_PINK,
                R_CONCRETE_PURPLE,
                R_CONCRETE_RED,
                R_CONCRETE_SILVER,
                R_CONCRETE_WHITE,
                R_CONCRETE_YELLOW,

                S_CONCRETE_BLACK,
                S_CONCRETE_BLUE,
                S_CONCRETE_BROWN,
                S_CONCRETE_CYAN,
                S_CONCRETE_GRAY,
                S_CONCRETE_GREEN,
                S_CONCRETE_LIGHT_BLUE,
                S_CONCRETE_LIME,
                S_CONCRETE_MAGENTA,
                S_CONCRETE_ORANGE,
                S_CONCRETE_PINK,
                S_CONCRETE_PURPLE,
                S_CONCRETE_RED,
                S_CONCRETE_SILVER,
                S_CONCRETE_WHITE,
                S_CONCRETE_YELLOW,

                T_CONCRETE_BLACK,
                T_CONCRETE_BLUE,
                T_CONCRETE_BROWN,
                T_CONCRETE_CYAN,
                T_CONCRETE_GRAY,
                T_CONCRETE_GREEN,
                T_CONCRETE_LIGHT_BLUE,
                T_CONCRETE_LIME,
                T_CONCRETE_MAGENTA,
                T_CONCRETE_ORANGE,
                T_CONCRETE_PINK,
                T_CONCRETE_PURPLE,
                T_CONCRETE_RED,
                T_CONCRETE_SILVER,
                T_CONCRETE_WHITE,
                T_CONCRETE_YELLOW,

                U_CONCRETE_BLACK,
                U_CONCRETE_BLUE,
                U_CONCRETE_BROWN,
                U_CONCRETE_CYAN,
                U_CONCRETE_GRAY,
                U_CONCRETE_GREEN,
                U_CONCRETE_LIGHT_BLUE,
                U_CONCRETE_LIME,
                U_CONCRETE_MAGENTA,
                U_CONCRETE_ORANGE,
                U_CONCRETE_PINK,
                U_CONCRETE_PURPLE,
                U_CONCRETE_RED,
                U_CONCRETE_SILVER,
                U_CONCRETE_WHITE,
                U_CONCRETE_YELLOW,

                V_CONCRETE_BLACK,
                V_CONCRETE_BLUE,
                V_CONCRETE_BROWN,
                V_CONCRETE_CYAN,
                V_CONCRETE_GRAY,
                V_CONCRETE_GREEN,
                V_CONCRETE_LIGHT_BLUE,
                V_CONCRETE_LIME,
                V_CONCRETE_MAGENTA,
                V_CONCRETE_ORANGE,
                V_CONCRETE_PINK,
                V_CONCRETE_PURPLE,
                V_CONCRETE_RED,
                V_CONCRETE_SILVER,
                V_CONCRETE_WHITE,
                V_CONCRETE_YELLOW,

                W_CONCRETE_BLACK,
                W_CONCRETE_BLUE,
                W_CONCRETE_BROWN,
                W_CONCRETE_CYAN,
                W_CONCRETE_GRAY,
                W_CONCRETE_GREEN,
                W_CONCRETE_LIGHT_BLUE,
                W_CONCRETE_LIME,
                W_CONCRETE_MAGENTA,
                W_CONCRETE_ORANGE,
                W_CONCRETE_PINK,
                W_CONCRETE_PURPLE,
                W_CONCRETE_RED,
                W_CONCRETE_SILVER,
                W_CONCRETE_WHITE,
                W_CONCRETE_YELLOW,

                X_CONCRETE_BLACK,
                X_CONCRETE_BLUE,
                X_CONCRETE_BROWN,
                X_CONCRETE_CYAN,
                X_CONCRETE_GRAY,
                X_CONCRETE_GREEN,
                X_CONCRETE_LIGHT_BLUE,
                X_CONCRETE_LIME,
                X_CONCRETE_MAGENTA,
                X_CONCRETE_ORANGE,
                X_CONCRETE_PINK,
                X_CONCRETE_PURPLE,
                X_CONCRETE_RED,
                X_CONCRETE_SILVER,
                X_CONCRETE_WHITE,
                X_CONCRETE_YELLOW,

                Y_CONCRETE_BLACK,
                Y_CONCRETE_BLUE,
                Y_CONCRETE_BROWN,
                Y_CONCRETE_CYAN,
                Y_CONCRETE_GRAY,
                Y_CONCRETE_GREEN,
                Y_CONCRETE_LIGHT_BLUE,
                Y_CONCRETE_LIME,
                Y_CONCRETE_MAGENTA,
                Y_CONCRETE_ORANGE,
                Y_CONCRETE_PINK,
                Y_CONCRETE_PURPLE,
                Y_CONCRETE_RED,
                Y_CONCRETE_SILVER,
                Y_CONCRETE_WHITE,
                Y_CONCRETE_YELLOW,

                Z_CONCRETE_BLACK,
                Z_CONCRETE_BLUE,
                Z_CONCRETE_BROWN,
                Z_CONCRETE_CYAN,
                Z_CONCRETE_GRAY,
                Z_CONCRETE_GREEN,
                Z_CONCRETE_LIGHT_BLUE,
                Z_CONCRETE_LIME,
                Z_CONCRETE_MAGENTA,
                Z_CONCRETE_ORANGE,
                Z_CONCRETE_PINK,
                Z_CONCRETE_PURPLE,
                Z_CONCRETE_RED,
                Z_CONCRETE_SILVER,
                Z_CONCRETE_WHITE,
                Z_CONCRETE_YELLOW,

        }).forEach(block -> {
            Preconditions.checkNotNull(block.getRegistryName(), "Registry name cannot be null!");
            registry.register(
                    ModUtil.setCreativeTab(
                            ModUtil.setRegistryNames(
                                    new ItemBlock(block),
                                    block.getRegistryName())
                    )
            );
        });

        // Items
        event.getRegistry().registerAll(
                setup(new ItemBase(), "glass_shard_black"),
                setup(new ItemBase(), "glass_shard_blue"),
                setup(new ItemBase(), "glass_shard_brown"),
                setup(new ItemBase(), "glass_shard_clear"),
                setup(new ItemBase(), "glass_shard_cyan"),
                setup(new ItemBase(), "glass_shard_gray"),
                setup(new ItemBase(), "glass_shard_green"),
                setup(new ItemBase(), "glass_shard_light_blue"),
                setup(new ItemBase(), "glass_shard_lime"),
                setup(new ItemBase(), "glass_shard_magenta"),
                setup(new ItemBase(), "glass_shard_orange"),
                setup(new ItemBase(), "glass_shard_pink"),
                setup(new ItemBase(), "glass_shard_purple"),
                setup(new ItemBase(), "glass_shard_red"),
                setup(new ItemBase(), "glass_shard_silver"),
                setup(new ItemBase(), "glass_shard_white"),
                setup(new ItemBase(), "glass_shard_yellow"),

                setup(new ItemGlassCutter(Item.ToolMaterial.DIAMOND), "cutter_glass_diamond"),
                setup(new ItemGlassCutter(Item.ToolMaterial.IRON), "cutter_glass_iron")
        );
        Main.CHARACTER_MOD_LOG.debug("Registered items");
    }

    // Setup Method
    @Nonnull
    public static <T extends IForgeRegistryEntry> T setup(@Nonnull final T entry, @Nonnull final String name) {
        return setup(entry, new ResourceLocation(MOD_ID, name));
    }

    @Nonnull
    public static <T extends IForgeRegistryEntry> T setup(@Nonnull final T entry, @Nonnull final ResourceLocation registryName) {
        entry.setRegistryName(registryName);
        if (entry instanceof Block) {
            ((Block) entry).setTranslationKey(MOD_ID + "." + registryName.getPath());
        }
        if (entry instanceof Item) {
            ((Item) entry).setTranslationKey(MOD_ID + "." + registryName.getPath());
        }
        return entry;
    }
}